spring:
  cloud:
    function:
      definition: orderCreated
#    stream:
#      function:
#        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8084

management:
  tracing:
    enabled: false
